#
# Default application configuration
#
# DO NOT EDIT THIS FILE DIRECTLY, instead
# use Config.ps1 to add or override configuration 
# settings if you don't like the defaults.
#

#
# Internal variables
#
$invocationPath = Split-Path $myInvocation.MyCommand.Path
$arch = (Get-WmiObject Win32_OperatingSystem).OSArchitecture

#
# Path for binaries
#
Set-Variable BinPath -Value "$invocationPath\bin" -Option ReadOnly

#
# Path for libraries
#
Set-Variable LibPath -Value "$invocationPath\lib" -Option ReadOnly

#
# FLAC Settings
#

# Specify full path to the FLAC executable
Set-Variable FlacExecutable -Value ($BinPath + "\flac") -Option ReadOnly

#
# PAR2 Settings
#

# Specify full path to the PAR2 executable
Set-Variable Par2Executable -Value ($BinPath + "\par2j" + (@{$true = "64"; $false = ""}[$arch -eq "64-bit"])) -Option ReadOnly

# Level of Redundancy (in %)
Set-Variable Par2Redundancy -Value 10 -Option ReadOnly

#
# Artwork
#

# Provide a list of extensions for bitmap files that should be considered when renaming artwork.
Set-Variable BitmapExt -Value "png|jpg|tif" -Option ReadOnly

#
# Audio Files
#

# Provide a list of extensions for audio files that should be considered when executing the scripts
Set-Variable AudioExt -Value "flac|mp3" -Option ReadOnly

#
# CUE sheets
#

# extensions for backup copy of original cue file (before performaing modifications)
Set-Variable CueSheetBackupExt -Value "orig" -Option ReadOnly

#
# Load user-defined configuration
#
if (Test-Path -PathType Leaf (Join-Path invocationPath Config.ps1))
{
    . (Join-Path $invocationPath Config.ps1)
}
